#!/bin/bash

echo "Original Run with gamma = .9 and pe =.01 and one-time initial outputs for initial questions \n"
python3 mdp.py --gamma=.9 --pe=.01 --output=all

echo "###########################################################################\n"

echo "Run with lower gamma = .5 and original pe =.01 \n"
python3 mdp.py --gamma=.5 --pe=.01 --output=opt

echo "###########################################################################\n"
echo "Run with lowest gamma = .01 and original pe =.01 \n"
python3 mdp.py --gamma=.1 --pe=.01 --output=opt

echo "###########################################################################\n"
echo "Run with original = .9 and higher error pe =.1 \n"
python3 mdp.py --gamma=.9 --pe=.1 --output=opt

echo "###########################################################################\n"
echo "Run with original = .9 and even higher error pe =.5 \n"
python3 mdp.py --gamma=.9 --pe=.5 --output=opt

echo "###########################################################################\n"
echo "Run with original = .9 and highest error pe =.9 \n"
python3 mdp.py --gamma=.9 --pe=.9 --output=opt

echo "###########################################################################\n"
echo "Run with lowest gamma = .1 and highest error pe =.9 \n"
python3 mdp.py --gamma=.1 --pe=.9 --output=opt